# Generated by Django 5.1.4 on 2025-01-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_selectedpetmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedpetmodel',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
