# Generated by Django 5.1.4 on 2025-01-01 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_adoptionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
