# Generated by Django 5.1.4 on 2025-01-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_adoptionmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
