# Generated by Django 5.1.4 on 2025-01-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_adoptionmodel_selected_pets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionmodel',
            name='selected_pets',
        ),
        migrations.AddField(
            model_name='adoptionmodel',
            name='selected_pets',
            field=models.ManyToManyField(to='users.selectedpetmodel'),
        ),
    ]
