# Generated by Django 5.1.4 on 2025-01-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_adoptionmodel_selected_pets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedpetmodel',
            name='is_adopted',
            field=models.BooleanField(default=False),
        ),
    ]
