# Generated by Django 5.1.4 on 2025-01-02 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_selectedpetmodel_is_adopted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
