# Generated by Django 5.1.4 on 2025-01-02 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_delete_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionmodel',
            name='selected_pets',
        ),
        migrations.AddField(
            model_name='adoptionmodel',
            name='selected_pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.selectedpetmodel'),
        ),
    ]
