# Generated by Django 5.1.4 on 2025-01-02 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_adoptionmodel_selected_pet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptionmodel',
            old_name='selected_pet',
            new_name='selected_pets',
        ),
    ]
