# Generated by Django 5.1.4 on 2025-01-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_selected_pet_adoptionmodel_selected_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedpetmodel',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
