# Generated by Django 5.1.4 on 2025-01-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petmodel',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
