# Generated by Django 5.1.4 on 2025-01-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_petmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmodel',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
