# Generated by Django 5.1.4 on 2025-01-01 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_infomodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoModel',
        ),
    ]
